[project]
name = "asistente-ia-upy"
version = "1.0.0"
description = "Asistente virtual de la Universidad Politécnica de Yucatán"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "python-dotenv",
    "chainlit>=2.9.6",
    "llama-index>=0.14.15",
    "llama-index-vector-stores-chroma>=0.5.5",
    "llama-index-readers-file>=0.5.6",
    "chromadb>=1.5.1",
    "llama-index-embeddings-huggingface>=0.6.1",
    "supabase>=2.28.0",
    "langfuse>=3.14.5",
    "torch",
]

[tool.uv.sources]
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
